### ISSUE TITLE
command "just flash" failed for "hello-world"  project

### ISSUE THREAD

**Issue by cekongnet** [drone-os/drone-core#13]
run  "just flash", failed , show the messages:
cannot find trait `AllocRef` in module `core::alloc`
  --> src/lib.rs:36:1
   |
36 | / heap! {
37 | |     /// A heap allocator generated from the `Drone.toml`.
38 | |     heap => pub Heap;
39 | | }
   | |_^ not found in `core::alloc`

**Comment by valff** [comment]
The fix is already on the master branch. It required some backward incompatible changes, so it will be a part of the next release 0.14 (presumably the end of March). Meanwhile an older Rust version can be used as a workaround, e.g. `nightly-2021-01-19`.

**Comment by cekongnet** [comment]
Compiled success！
with run "drone new --toolchain nightly-2020-11-25 --device stm32f407 --flash-size 128K --ram-size 20K hello-world",
then, "cd hello-world" , run "just deps","just flash"
