### ISSUE TITLE
Support for RISC-V based processors

### ISSUE THREAD

**Issue by nikunjkumarnakum** [drone-os/drone-core#14]
When it is expected to see support for RISC-V based processors or microprocessors.

**Comment by valff** [comment]
It's almost there. I'm currently working on a demo app for HiFive1 dev board. There are troubles with incomplete atomics support in the Freedom E310 core.

**Comment by gitlarky** [comment]
Hi Valentine:

I am so delighted to see your progress on Drone OS. Are you planning to include the support  to pixhawk open hardware in the future? If yes, when might be the time frame? Thank you very much!

Best regards!

Zhenyu Xu
Southern University of Science & Technology
________________________________

**Comment by valff** [comment]
Hi @gitlarky, despite the project name, we are not working with flying robots (yet). However I have taken a look at Pixhawk, and looks like it contains STM32F4 and STM32F1 chips, which are well-supported by Drone OS. So all is needed is to write drivers for the specific peripherals that come with the board.

**Comment by valff** [comment]
RISC-V experimental support is released today. Here is our demo app: https://github.com/drone-os/longan-blink

**Comment by gitlarky** [comment]
Thanks, Valentine!

Zhenyu Xu
Southern University of Science & Technology
________________________________

**Comment by nikunjkumarnakum** [comment]
thank you so much
