### ISSUE TITLE
drone-core does not compile with recent nightlies

### ISSUE THREAD

**Issue by samueltardieu** [drone-os/drone-core#4]
It looks like the `unions_with_drop_fields` lint has disappeared in recent nightlies:

```
   Compiling drone-core v0.10.1 (/home/sam/Dev/drone-core)
warning: unknown lint: `unions_with_drop_fields`
   --> src/proc_loop.rs:123:9
    |
123 | #[allow(unions_with_drop_fields)]
```

This gives the following error when compiling an application:

```
   Compiling drone-core v0.10.1
error[E0740]: unions may not contain fields that need dropping
   --> /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/drone-core-0.10.1/src/proc_loop.rs:126:5
    |
126 |     cmd: Cmd,
    |     ^^^^^^^^
    |
note: `std::mem::ManuallyDrop` can be used to wrap the type
```

A cleaner solution exist using `code::mem::ManuallyDrop` as suggested which clearly expresses intent.

**Comment by valff** [comment]
Already done it at 55effd184f5c7028077829bedec33021696af834. Sorry, it was committed earlier, but has not been pushed. I'm preparing a new 0.11 release with some breaking changes, will release it soon.

**Comment by samueltardieu** [comment]
Perfect, one of my students got hit by that, we're waiting for the release then. Thanks!
