### ISSUE TITLE
Fail to flash hello-world project

### ISSUE THREAD

**Issue by bodagovsky** [drone-os/drone-core#9]
Following the drone book
when trying to ```just flash``` get this error 
```artur@artur-computer:~/hello-world-2$ just flash
drone env thumbv7m-none-eabi -- cargo build --features "" --release
    Finished release [optimized + debuginfo] target(s) in 0.08s
drone flash target/thumbv7m-none-eabi/release/hello-world-2
Black Magic Probe (Firmware v1.7.1-1-g2fdd94a) (Hardware Version 1)
Copyright (C) 2015  Black Sphere Technologies Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Assert SRST during connect: enabled
Timeout during scan. Is target stuck in WFI?
SW-DP scan failed!
/run/user/1000/.tmpAIYBMJ:60: Error in sourced command file:
Attaching to Remote target failed
Error: `"gdb-multiarch" "target/thumbv7m-none-eabi/release/hello-world-2" "--quiet" "--nx" "--batch" "--command" "/run/user/1000/.tmpAIYBMJ"` exited with status code: 1
error: Recipe `flash` failed on line 63 with exit code 1```
what may cause this problem?

**Comment by alfredch** [comment]
Your BMP probe fails to connect to the target.
Please verify your wiring with the 'Getting-Started' instructions in the BlackMagic Wiki:
https://github.com/blacksphere/blackmagic/wiki/Getting-Started
As long as SW-DP scan fails, you cannot 'just flash'.

**Comment by bodagovsky** [comment]
well, nothing wrong with wiring, but connection verification fails. I flashed ```blackmagic_dfu``` using st-link v2 instead of usb-uart. Can this be the issue?

**Comment by alfredch** [comment]
Your console output shows that the BMP firmware is present and responding.
Alternatively, you could setup the demo project for flashing with st-link instead of bmp.

**Comment by bodagovsky** [comment]
In this case I should use ```just flash``` or should I switch to ```./stm32loader``` for example?

**Comment by alfredch** [comment]
Drone uses openocd for flashing with st-link.
That means that you have to install openocd on your PC.
For the hello-world, you could create a project like this:
drone new --device stm32f103 --flash-size 128K --ram-size 20K hello-world --toolchain nightly-2020-04-30 --probe openocd
Then you can execute 'just flash'.

**Comment by alfredch** [comment]
Hint: Many people have a BluePill with the Chinese clone (fake?) STM32 chips called CS32F103C8T6 instead of a real STM32F103C8T6.
In that case, you have to modify the openocd configuration file named 'stm32f1x.cfg'. On my pc (Ubuntu 18.04), it is located in the directory /usr/local/share/openocd/scripts/target. See this blog post for the details what has to be changed:
https://community.platformio.org/t/cannot-upload-to-stm32-bluepill-board-over-stlink-v2/3492
Maybe that could also be the reason why flashing with bmp fails?

**Comment by bodagovsky** [comment]
no, I am sure that I am using the original one

**Comment by bodagovsky** [comment]
on some reasons I have this output
<img width="651" alt="Снимок экрана 2020-10-20 в 16 18 49" src="https://user-images.githubusercontent.com/48064608/96591455-f1e91480-12ef-11eb-942f-f70f2a81edf3.png">

but when i try to scan
<img width="247" alt="Снимок экрана 2020-10-20 в 16 20 00" src="https://user-images.githubusercontent.com/48064608/96591626-1fce5900-12f0-11eb-8c76-8045a2566f04.png">

**Comment by alfredch** [comment]
I get that same failure (SW-DP scan failed) only when the target is not powered on.
However, I am currently using a different bmp probe clone, no BluePill.

**Comment by bodagovsky** [comment]
![IMAGE 2020-10-20 17:28:33](https://user-images.githubusercontent.com/48064608/96600511-ae93a380-12f9-11eb-9c98-0f017b90a05c.jpg)
look like everything wired up correctly
I don't know what else can be wrong

**Comment by bodagovsky** [comment]
target : top
bmp : bottom

**Comment by alfredch** [comment]
Is the target a new Blue Pill or was something else flashed to it before you tried to flash your demo firmware?
Maybe the target is locked somehow and needs an flash-erase?

**Comment by alfredch** [comment]
The best way to verify if the target is ok is probably be the openocd/st-link v2 route.

**Comment by bodagovsky** [comment]
probably I tried something. I'll check

**Comment by bodagovsky** [comment]
<img width="768" alt="Снимок экрана 2020-10-20 в 18 05 09" src="https://user-images.githubusercontent.com/48064608/96605364-cc173c00-12fe-11eb-80f2-bcbfd3868791.png">
st-util command outputs this

but with reset button pressed the output is 
<img width="745" alt="Снимок экрана 2020-10-20 в 18 05 48" src="https://user-images.githubusercontent.com/48064608/96605444-e3eec000-12fe-11eb-853a-65b5f5c622a9.png">

**Comment by alfredch** [comment]
Doesn't look sane. Here we get:
`st-util
2020-10-20T17:36:24 INFO common.c: F1xx Medium-density: 20 KiB SRAM, 63693 KiB flash in at least 1 KiB pages.
2020-10-20T17:36:24 INFO gdb-server.c: Listening at *:4242...`

**Comment by bodagovsky** [comment]
I have fixed wiring recently
now ```monitor swdp_scan```behaves as desired 
but ```just flash``` still crashes with
<img width="1113" alt="Снимок экрана 2020-11-06 в 16 50 06" src="https://user-images.githubusercontent.com/48064608/98373321-224ee380-2050-11eb-9512-e36b4e2d090e.png">
I have MacOS

**Comment by bodagovsky** [comment]
on Linux I flashed successfully, but right after that I commanded ```just log``` and swdp scan fails again. Looks like target blocks, bacause after erasing and rebooting, everything remains the same, first time swdp scan success -> flash -> swdp_scan fails

**Comment by alfredch** [comment]
The Drone-OS tools are not tested on MacOS yet.
You say, on Linux, the `just flash` works the first time after you erase the target flash. After the `just flash,` before you execute `just log` does` the `monitor swdp_scan` still work?

**Comment by bodagovsky** [comment]
after ```just flash``` swdp_scan immediatly fails

**Comment by alfredch** [comment]
That's weird. Would you mind making a zip, 7z- or rar-archive of your complete project folder (without the target directory) and send it to alfred.keller@gmail.com? I can verify it on the hardware setup as described in 'the book'.

**Comment by bodagovsky** [comment]
yeah. I Also have question about specifying serial-endpoint at this section
```[log.swo]
reset-freq = 8000000
baud-rate = 115200
serial-endpoint =```
as I have ```ttyACM0``` on my Ubuntu instead of  ```ttyBmpGdb```

**Comment by bodagovsky** [comment]
> That's weird. Would you mind making a zip, 7z- or rar-archive of your complete project folder (without the target directory) and send it to [alfred.keller@gmail.com](mailto:alfred.keller@gmail.com)? I can verify it on the hardware setup as described in 'the book'.

I would rather upload it on github if you don't mind

**Comment by alfredch** [comment]
The serial endpoint should only be configured in Drone.toml if you use a separate UART/USB adapter. If you have such a device, you will see its device name with `ls /dev/tty*`. It cannot be `/dev/tttyxBmpGdb` nor `/dev/ttyBmpTarg`, as those are created and used by the bmp probe.
Github upload is ok.

**Comment by alfredch** [comment]
Note: /dev/ttyBmpGdb typically links to /dev/ttyACM0, so it is wrong to set it as serial-endpoint in case you have an external converter.

**Comment by bodagovsky** [comment]
https://github.com/bodagovsky/drone-project
